# Generated by Django 6.0.5 on 2026-06-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="班级名称"
                    ),
                ),
                ("grade", models.CharField(max_length=10, verbose_name="年级")),
                ("major", models.CharField(max_length=50, verbose_name="专业")),
                ("class_number", models.CharField(max_length=10, verbose_name="班号")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
                "ordering": ["grade", "major", "class_number"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="仅教师角色需要填写，全局唯一",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="工号",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="real_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="必填",
                max_length=50,
                verbose_name="真实姓名",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="class_info",
            field=models.ForeignKey(
                blank=True,
                help_text="学生所属班级",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="users.classinfo",
                verbose_name="班级",
            ),
        ),
    ]
