# Generated by Django 6.0.5 on 2026-06-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_classinfo_and_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="首次登录后强制修改密码",
                verbose_name="需修改密码",
            ),
        ),
    ]
