# Generated by Django 6.0.5 on 2026-05-31 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "template_code",
                    models.CharField(
                        choices=[
                            ("practice_completed", "练习完成"),
                            ("practice_score_high", "成绩优秀"),
                            ("practice_score_low", "成绩警告"),
                            ("material_published", "资料发布"),
                            ("assignment_due", "作业即将到期"),
                            ("assignment_overdue", "作业已逾期"),
                            ("system_maintenance", "系统维护"),
                            ("new_feature", "新功能发布"),
                            ("mentioned", "被@提及"),
                            ("comment_replied", "评论回复"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="模板代码",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="使用 {variable} 占位符",
                        max_length=200,
                        verbose_name="标题模板",
                    ),
                ),
                (
                    "content_template",
                    models.TextField(
                        help_text="支持 {variable} 和 HTML", verbose_name="内容模板"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "系统通知"),
                            ("learning", "学习任务"),
                            ("practice", "练习成绩"),
                            ("interaction", "互动消息"),
                            ("announcement", "公告"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="默认优先级",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_persistent",
                    models.BooleanField(default=True, verbose_name="是否持久化"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Element Plus 图标名称或emoji",
                        max_length=50,
                        verbose_name="图标",
                    ),
                ),
                (
                    "link_pattern",
                    models.URLField(
                        blank=True,
                        help_text="使用 {id} 等占位符生成链接",
                        max_length=500,
                        verbose_name="链接模式",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "通知模板",
                "verbose_name_plural": "通知模板",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "系统通知"),
                            ("learning", "学习任务"),
                            ("practice", "练习成绩"),
                            ("interaction", "互动消息"),
                            ("announcement", "公告"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知标题")),
                (
                    "content",
                    models.TextField(help_text="支持HTML格式", verbose_name="通知内容"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否已读"
                    ),
                ),
                (
                    "is_persistent",
                    models.BooleanField(
                        default=True,
                        help_text="True: 保存到数据库; False: 仅实时推送",
                        verbose_name="是否持久化",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="点击通知后跳转的页面",
                        max_length=500,
                        verbose_name="跳转链接",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="关联的学习资料/练习记录等",
                        null=True,
                        verbose_name="关联对象ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="过期后自动标记已读并归档",
                        null=True,
                        verbose_name="过期时间",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储额外信息，如图标、颜色等",
                        verbose_name="元数据",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="关联对象类型",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收用户",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知列表",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type", "-created_at"],
                        name="notificatio_recipie_7b2be0_idx",
                    ),
                    models.Index(
                        fields=["recipient", "priority", "is_read"],
                        name="notificatio_recipie_299942_idx",
                    ),
                ],
            },
        ),
    ]
