# Generated by Django 6.0.4 on 2026-05-04 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(verbose_name='用户提示词')),
                ('system_prompt', models.TextField(default='', verbose_name='系统提示词(场景)')),
                ('llm_response', models.TextField(blank=True, verbose_name='大模型原始回复')),
                ('scores', models.JSONField(default=dict, verbose_name='评分数据')),
                ('suggestions', models.TextField(blank=True, verbose_name='修改建议')),
                ('overall_score', models.IntegerField(default=0, verbose_name='综合得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
