# Generated by Django 6.0.5 on 2026-06-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_enhance_practice_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="显示名称")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("ollama", "Ollama本地"),
                            ("qwen", "通义千问"),
                            ("deepseek", "DeepSeek"),
                            ("custom", "自定义"),
                        ],
                        default="custom",
                        max_length=50,
                        verbose_name="提供商",
                    ),
                ),
                ("api_url", models.CharField(max_length=500, verbose_name="API地址")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API密钥"
                    ),
                ),
                (
                    "model_id",
                    models.CharField(max_length=100, verbose_name="模型标识符"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认模型"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM模型配置",
                "verbose_name_plural": "LLM模型配置",
                "ordering": ["-is_default", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("owner", "is_default"),
                        name="unique_default_llm_per_user",
                    )
                ],
            },
        ),
    ]
