# Generated by Django 6.0.4 on 2026-05-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('basic', '基础入门'), ('intermediate', '进阶技巧'), ('advanced', '高级应用'), ('best_practices', '最佳实践')], default='basic', max_length=20, verbose_name='分类')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习资料',
                'verbose_name_plural': '学习资料',
                'ordering': ['order_index', '-created_at'],
            },
        ),
    ]
