# Generated by Django 6.0.5 on 2026-05-31 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningmaterial",
            options={
                "ordering": ["-order_index", "-created_at"],
                "verbose_name": "学习资料",
                "verbose_name_plural": "学习资料",
            },
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_materials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="cover_image",
            field=models.URLField(blank=True, default="", verbose_name="封面图片"),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "已发布"),
                    ("archived", "已下架"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="summary",
            field=models.TextField(blank=True, default="", verbose_name="摘要"),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="标签列表"),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="阅读量"),
        ),
        migrations.AlterField(
            model_name="learningmaterial",
            name="order_index",
            field=models.IntegerField(default=0, verbose_name="排序权重"),
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(
                fields=["category", "status"], name="learning_le_categor_74c7ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(
                fields=["status", "-created_at"], name="learning_le_status_b65b2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningmaterial",
            index=models.Index(
                fields=["author", "-created_at"], name="learning_le_author__1d01c7_idx"
            ),
        ),
    ]
