# Generated by Django 6.0.5 on 2026-06-06 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_alter_learningmaterial_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[("like", "点赞"), ("favorite", "收藏")],
                        max_length=20,
                        verbose_name="交互类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="learning.learningmaterial",
                        verbose_name="学习资料",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "资料交互",
                "verbose_name_plural": "资料交互",
                "indexes": [
                    models.Index(
                        fields=["material", "interaction_type"],
                        name="learning_ma_materia_5befd7_idx",
                    ),
                    models.Index(
                        fields=["user", "interaction_type"],
                        name="learning_ma_user_id_ec75ba_idx",
                    ),
                ],
                "unique_together": {("user", "material", "interaction_type")},
            },
        ),
    ]
