# Generated by Django 6.0.4 on 2026-05-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(max_length=50, unique=True, verbose_name='场景ID')),
                ('title', models.CharField(max_length=100, verbose_name='场景标题')),
                ('description', models.TextField(verbose_name='场景描述')),
                ('icon', models.CharField(default='🎯', max_length=50, verbose_name='图标')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=20, verbose_name='难度')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '练习场景',
                'verbose_name_plural': '练习场景',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='practicerecord',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.practicescenario', verbose_name='练习场景'),
        ),
        migrations.CreateModel(
            name='PracticeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.IntegerField(verbose_name='主题编号')),
                ('title', models.CharField(max_length=200, verbose_name='主题标题')),
                ('description', models.TextField(verbose_name='主题描述')),
                ('example_prompt', models.TextField(blank=True, verbose_name='示例提示词')),
                ('evaluation_criteria', models.JSONField(default=dict, verbose_name='评估标准')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='practice.practicescenario', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '练习主题',
                'verbose_name_plural': '练习主题',
                'ordering': ['topic_number'],
                'unique_together': {('scenario', 'topic_number')},
            },
        ),
        migrations.AddField(
            model_name='practicerecord',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.practicetopic', verbose_name='选择的主题'),
        ),
    ]
