# Generated by Django 6.0.4 on 2026-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_add_scenario_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerecord',
            name='duration_seconds',
            field=models.IntegerField(default=0, verbose_name='练习时长(秒)'),
        ),
        migrations.AddField(
            model_name='practicerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
