# Generated by Django 6.0.5 on 2026-05-31 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_add_duration_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicescenario",
            options={
                "ordering": ["-order", "-created_at"],
                "verbose_name": "练习场景",
                "verbose_name_plural": "练习场景",
            },
        ),
        migrations.AlterModelOptions(
            name="practicetopic",
            options={
                "ordering": ["order", "topic_number"],
                "verbose_name": "练习主题",
                "verbose_name_plural": "练习主题",
            },
        ),
        migrations.AddField(
            model_name="practicerecord",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.AddField(
            model_name="practicerecord",
            name="feedback",
            field=models.TextField(blank=True, verbose_name="学生反馈"),
        ),
        migrations.AddField(
            model_name="practicerecord",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="是否完成"),
        ),
        migrations.AddField(
            model_name="practicerecord",
            name="score_level",
            field=models.CharField(
                choices=[
                    ("excellent", "优秀 (90-100)"),
                    ("good", "良好 (80-89)"),
                    ("average", "中等 (70-79)"),
                    ("needs_improvement", "待提高 (60-69)"),
                    ("poor", "较差 (<60)"),
                ],
                default="average",
                max_length=20,
                verbose_name="成绩等级",
            ),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_scenarios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="avg_score",
            field=models.FloatField(default=0, verbose_name="平均分"),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="cover_image",
            field=models.URLField(blank=True, null=True, verbose_name="封面图片"),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="practice_count",
            field=models.PositiveIntegerField(default=0, verbose_name="练习次数"),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "已发布"),
                    ("archived", "已下架"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新时间"
            ),
        ),
        migrations.AddField(
            model_name="practicescenario",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="查看次数"),
        ),
        migrations.AddField(
            model_name="practicetopic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="practicetopic",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="practicetopic",
            name="max_score",
            field=models.IntegerField(default=100, verbose_name="满分"),
        ),
        migrations.AddField(
            model_name="practicetopic",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.AddField(
            model_name="practicetopic",
            name="time_limit_minutes",
            field=models.IntegerField(default=30, verbose_name="时间限制(分钟)"),
        ),
        migrations.AddField(
            model_name="practicetopic",
            name="topic_type",
            field=models.CharField(
                choices=[
                    ("standard", "标准题"),
                    ("challenge", "挑战题"),
                    ("bonus", "加分题"),
                ],
                default="standard",
                max_length=20,
                verbose_name="题目类型",
            ),
        ),
        migrations.AddField(
            model_name="practicetopic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="practicescenario",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序权重"),
        ),
        migrations.AddIndex(
            model_name="practicerecord",
            index=models.Index(
                fields=["user", "-created_at"], name="practice_pr_user_id_df6231_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practicerecord",
            index=models.Index(
                fields=["scenario", "-overall_score"],
                name="practice_pr_scenari_931dd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="practicerecord",
            index=models.Index(
                fields=["score_level"], name="practice_pr_score_l_ccd831_idx"
            ),
        ),
    ]
